$functionFolders = @('functions', 'helpers')
ForEach ($folder in $functionFolders)
{
    $folderPath = Join-Path -Path $PSScriptRoot -ChildPath $folder
    If (Test-Path -Path $folderPath)
    {
        Write-Verbose -Message "Importing from $folder"
        $functions = Get-ChildItem -Path $folderPath -Filter '*.ps1'
        ForEach ($function in $functions)
        {
            Write-Verbose -Message "  Importing $($function.BaseName)"
            . $function.FullName
        }
    }
}
Export-ModuleMember -Function Get-WUGProduct
Export-ModuleMember -Function Add-WUGDeviceTemplate
Export-ModuleMember -Function Add-WUGDeviceTemplates
Export-ModuleMember -Function Add-WUGMonitorTemplate
Export-ModuleMember -Function Set-WUGDeviceTemplate
Export-ModuleMember -Function Invoke-WUGDeviceRefresh
Export-ModuleMember -Function Get-WUGActiveMonitor
Export-ModuleMember -Function Set-WUGActiveMonitor
Export-ModuleMember -Function Add-WUGActiveMonitorToDevice
Export-ModuleMember -Function Get-WUGMonitorTemplate
Export-ModuleMember -Function Import-WUGMonitorTemplate
Export-ModuleMember -Function Add-WUGActiveMonitor
Export-ModuleMember -Function Remove-WUGActiveMonitor
Export-ModuleMember -Function Add-WUGDevice
Export-ModuleMember -Function Connect-WUGServer
Export-ModuleMember -Function Disconnect-WUGServer
Export-ModuleMember -Function Get-WUGDevice
Export-ModuleMember -Function Get-WUGDeviceAttribute
Export-ModuleMember -Function Get-WUGDeviceReportCPU
Export-ModuleMember -Function Get-WUGDeviceReportDiskSpaceFree
Export-ModuleMember -Function Get-WUGDeviceReportDisk
Export-ModuleMember -Function Get-WUGDeviceReportInterface
Export-ModuleMember -Function Get-WUGDeviceReportInterfaceDiscards
Export-ModuleMember -Function Get-WUGDeviceReportInterfaceErrors
Export-ModuleMember -Function Get-WUGDeviceReportInterfaceTraffic
Export-ModuleMember -Function Get-WUGDeviceReportMemory
Export-ModuleMember -Function Get-WUGDeviceReportPingAvailability
Export-ModuleMember -Function Get-WUGDeviceReportPingResponseTime
Export-ModuleMember -Function Get-WUGDeviceReportStateChange
Export-ModuleMember -Function Get-WUGDeviceGroup
Export-ModuleMember -Function Get-WUGDeviceGroupReportCpu
Export-ModuleMember -Function Get-WUGDeviceGroupReportDiskSpaceFree
Export-ModuleMember -Function Get-WUGDeviceGroupReportDisk
Export-ModuleMember -Function Get-WUGDeviceGroupReportInterfaceDiscards
Export-ModuleMember -Function Get-WUGDeviceGroupReportInterfaceErrors
Export-ModuleMember -Function Get-WUGDeviceGroupReportInterfaceTraffic
Export-ModuleMember -Function Get-WUGDeviceGroupReportInterface
Export-ModuleMember -Function Get-WUGDeviceGroupReportMaintenance
Export-ModuleMember -Function Get-WUGDeviceGroupReportMemory
Export-ModuleMember -Function Get-WUGDeviceGroupReportPingAvailability
Export-ModuleMember -Function Get-WUGDeviceGroupReportPingResponseTime
Export-ModuleMember -Function Get-WUGDeviceGroupReportStateChange
Export-ModuleMember -Function Get-WUGDeviceMaintenanceSchedule
Export-ModuleMember -Function Set-WUGDeviceMaintenanceSchedule
Export-ModuleMember -Function Get-WUGDeviceProperties
Export-ModuleMember -Function Get-WUGDeviceTemplate
Export-ModuleMember -Function Remove-WUGDevice
Export-ModuleMember -Function Remove-WUGDevices
Export-ModuleMember -Function Set-WUGDeviceAttribute
Export-ModuleMember -Function Set-WUGDeviceMaintenance
Export-ModuleMember -Function Set-WUGDeviceProperties
Export-ModuleMember -Function Get-WUGDeviceReport
Export-ModuleMember -Function Get-WUGDeviceGroupReport
Export-ModuleMember -Function Get-WUGDeviceScan
Export-ModuleMember -Function Get-WUGDeviceRole
Export-ModuleMember -Function Set-WUGDeviceRole
Export-ModuleMember -Function Get-WUGRole
Export-ModuleMember -Function Set-WUGRole
Export-ModuleMember -Function Import-WUGRoleTemplate
Export-ModuleMember -Function Export-WUGRoleTemplate
Export-ModuleMember -Function Get-WUGCredential
Export-ModuleMember -Function Add-WUGCredential
Export-ModuleMember -Function Set-WUGCredential
Export-ModuleMember -Function Get-WUGDeviceInterface
Export-ModuleMember -Function Get-WUGDeviceStatus
Export-ModuleMember -Function Get-WUGDeviceCredential
Export-ModuleMember -Function Set-WUGDeviceCredential
Export-ModuleMember -Function Invoke-WUGDevicePollNow
Export-ModuleMember -Function Get-WUGDeviceGroupMembership
Export-ModuleMember -Function Get-WUGDevicePollingConfig
Export-ModuleMember -Function Set-WUGDeviceInterface
Export-ModuleMember -Function Set-WUGDevicePollingConfig
Export-ModuleMember -Function Set-WUGDeviceGroup
Export-ModuleMember -Function Remove-WUGDeviceAttribute
Export-ModuleMember -Function Add-WUGDeviceInterface
Export-ModuleMember -Function Remove-WUGDeviceInterface
Export-ModuleMember -Function Remove-WUGDeviceMonitor
Export-ModuleMember -Function Remove-WUGDeviceGroup
Export-ModuleMember -Function Add-WUGDeviceGroup
Export-ModuleMember -Function Add-WUGDeviceGroupMember
Export-ModuleMember -Function Remove-WUGDeviceGroupMember
Export-ModuleMember -Function Add-WUGPerformanceMonitor
Export-ModuleMember -Function Add-WUGPerformanceMonitorToDevice
Export-ModuleMember -Function Add-WUGPassiveMonitor
Export-ModuleMember -Function Add-WUGPassiveMonitorToDevice
Export-ModuleMember -Function Get-WUGPassiveMonitor
Export-ModuleMember -Function Set-WUGPassiveMonitor
Export-ModuleMember -Function Remove-WUGPassiveMonitor
Export-ModuleMember -Function Set-WUGMonitorTemplate
Export-ModuleMember -Function Set-WUGDeviceGroupMembership
Export-ModuleMember -Function Get-WUGPerformanceMonitor
Export-ModuleMember -Function Set-WUGPerformanceMonitor


# SIG # Begin signature block
# MIIVlwYJKoZIhvcNAQcCoIIViDCCFYQCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCDFgiXnWOHeeMGs
# 66UW0VOoQNdXWP7nP00rjDYExmNV8KCCEdMwggVvMIIEV6ADAgECAhBI/JO0YFWU
# jTanyYqJ1pQWMA0GCSqGSIb3DQEBDAUAMHsxCzAJBgNVBAYTAkdCMRswGQYDVQQI
# DBJHcmVhdGVyIE1hbmNoZXN0ZXIxEDAOBgNVBAcMB1NhbGZvcmQxGjAYBgNVBAoM
# EUNvbW9kbyBDQSBMaW1pdGVkMSEwHwYDVQQDDBhBQUEgQ2VydGlmaWNhdGUgU2Vy
# dmljZXMwHhcNMjEwNTI1MDAwMDAwWhcNMjgxMjMxMjM1OTU5WjBWMQswCQYDVQQG
# EwJHQjEYMBYGA1UEChMPU2VjdGlnbyBMaW1pdGVkMS0wKwYDVQQDEyRTZWN0aWdv
# IFB1YmxpYyBDb2RlIFNpZ25pbmcgUm9vdCBSNDYwggIiMA0GCSqGSIb3DQEBAQUA
# A4ICDwAwggIKAoICAQCN55QSIgQkdC7/FiMCkoq2rjaFrEfUI5ErPtx94jGgUW+s
# hJHjUoq14pbe0IdjJImK/+8Skzt9u7aKvb0Ffyeba2XTpQxpsbxJOZrxbW6q5KCD
# J9qaDStQ6Utbs7hkNqR+Sj2pcaths3OzPAsM79szV+W+NDfjlxtd/R8SPYIDdub7
# P2bSlDFp+m2zNKzBenjcklDyZMeqLQSrw2rq4C+np9xu1+j/2iGrQL+57g2extme
# me/G3h+pDHazJyCh1rr9gOcB0u/rgimVcI3/uxXP/tEPNqIuTzKQdEZrRzUTdwUz
# T2MuuC3hv2WnBGsY2HH6zAjybYmZELGt2z4s5KoYsMYHAXVn3m3pY2MeNn9pib6q
# RT5uWl+PoVvLnTCGMOgDs0DGDQ84zWeoU4j6uDBl+m/H5x2xg3RpPqzEaDux5mcz
# mrYI4IAFSEDu9oJkRqj1c7AGlfJsZZ+/VVscnFcax3hGfHCqlBuCF6yH6bbJDoEc
# QNYWFyn8XJwYK+pF9e+91WdPKF4F7pBMeufG9ND8+s0+MkYTIDaKBOq3qgdGnA2T
# OglmmVhcKaO5DKYwODzQRjY1fJy67sPV+Qp2+n4FG0DKkjXp1XrRtX8ArqmQqsV/
# AZwQsRb8zG4Y3G9i/qZQp7h7uJ0VP/4gDHXIIloTlRmQAOka1cKG8eOO7F/05QID
# AQABo4IBEjCCAQ4wHwYDVR0jBBgwFoAUoBEKIz6W8Qfs4q8p74Klf9AwpLQwHQYD
# VR0OBBYEFDLrkpr/NZZILyhAQnAgNpFcF4XmMA4GA1UdDwEB/wQEAwIBhjAPBgNV
# HRMBAf8EBTADAQH/MBMGA1UdJQQMMAoGCCsGAQUFBwMDMBsGA1UdIAQUMBIwBgYE
# VR0gADAIBgZngQwBBAEwQwYDVR0fBDwwOjA4oDagNIYyaHR0cDovL2NybC5jb21v
# ZG9jYS5jb20vQUFBQ2VydGlmaWNhdGVTZXJ2aWNlcy5jcmwwNAYIKwYBBQUHAQEE
# KDAmMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5jb21vZG9jYS5jb20wDQYJKoZI
# hvcNAQEMBQADggEBABK/oe+LdJqYRLhpRrWrJAoMpIpnuDqBv0WKfVIHqI0fTiGF
# OaNrXi0ghr8QuK55O1PNtPvYRL4G2VxjZ9RAFodEhnIq1jIV9RKDwvnhXRFAZ/ZC
# J3LFI+ICOBpMIOLbAffNRk8monxmwFE2tokCVMf8WPtsAO7+mKYulaEMUykfb9gZ
# pk+e96wJ6l2CxouvgKe9gUhShDHaMuwV5KZMPWw5c9QLhTkg4IUaaOGnSDip0TYl
# d8GNGRbFiExmfS9jzpjoad+sPKhdnckcW67Y8y90z7h+9teDnRGWYpquRRPaf9xH
# +9/DUp/mBlXpnYzyOmJRvOwkDynUWICE5EV7WtgwggYaMIIEAqADAgECAhBiHW0M
# UgGeO5B5FSCJIRwKMA0GCSqGSIb3DQEBDAUAMFYxCzAJBgNVBAYTAkdCMRgwFgYD
# VQQKEw9TZWN0aWdvIExpbWl0ZWQxLTArBgNVBAMTJFNlY3RpZ28gUHVibGljIENv
# ZGUgU2lnbmluZyBSb290IFI0NjAeFw0yMTAzMjIwMDAwMDBaFw0zNjAzMjEyMzU5
# NTlaMFQxCzAJBgNVBAYTAkdCMRgwFgYDVQQKEw9TZWN0aWdvIExpbWl0ZWQxKzAp
# BgNVBAMTIlNlY3RpZ28gUHVibGljIENvZGUgU2lnbmluZyBDQSBSMzYwggGiMA0G
# CSqGSIb3DQEBAQUAA4IBjwAwggGKAoIBgQCbK51T+jU/jmAGQ2rAz/V/9shTUxjI
# ztNsfvxYB5UXeWUzCxEeAEZGbEN4QMgCsJLZUKhWThj/yPqy0iSZhXkZ6Pg2A2NV
# DgFigOMYzB2OKhdqfWGVoYW3haT29PSTahYkwmMv0b/83nbeECbiMXhSOtbam+/3
# 6F09fy1tsB8je/RV0mIk8XL/tfCK6cPuYHE215wzrK0h1SWHTxPbPuYkRdkP05Zw
# mRmTnAO5/arnY83jeNzhP06ShdnRqtZlV59+8yv+KIhE5ILMqgOZYAENHNX9SJDm
# +qxp4VqpB3MV/h53yl41aHU5pledi9lCBbH9JeIkNFICiVHNkRmq4TpxtwfvjsUe
# dyz8rNyfQJy/aOs5b4s+ac7IH60B+Ja7TVM+EKv1WuTGwcLmoU3FpOFMbmPj8pz4
# 4MPZ1f9+YEQIQty/NQd/2yGgW+ufflcZ/ZE9o1M7a5Jnqf2i2/uMSWymR8r2oQBM
# dlyh2n5HirY4jKnFH/9gRvd+QOfdRrJZb1sCAwEAAaOCAWQwggFgMB8GA1UdIwQY
# MBaAFDLrkpr/NZZILyhAQnAgNpFcF4XmMB0GA1UdDgQWBBQPKssghyi47G9IritU
# pimqF6TNDDAOBgNVHQ8BAf8EBAMCAYYwEgYDVR0TAQH/BAgwBgEB/wIBADATBgNV
# HSUEDDAKBggrBgEFBQcDAzAbBgNVHSAEFDASMAYGBFUdIAAwCAYGZ4EMAQQBMEsG
# A1UdHwREMEIwQKA+oDyGOmh0dHA6Ly9jcmwuc2VjdGlnby5jb20vU2VjdGlnb1B1
# YmxpY0NvZGVTaWduaW5nUm9vdFI0Ni5jcmwwewYIKwYBBQUHAQEEbzBtMEYGCCsG
# AQUFBzAChjpodHRwOi8vY3J0LnNlY3RpZ28uY29tL1NlY3RpZ29QdWJsaWNDb2Rl
# U2lnbmluZ1Jvb3RSNDYucDdjMCMGCCsGAQUFBzABhhdodHRwOi8vb2NzcC5zZWN0
# aWdvLmNvbTANBgkqhkiG9w0BAQwFAAOCAgEABv+C4XdjNm57oRUgmxP/BP6YdURh
# w1aVcdGRP4Wh60BAscjW4HL9hcpkOTz5jUug2oeunbYAowbFC2AKK+cMcXIBD0Zd
# OaWTsyNyBBsMLHqafvIhrCymlaS98+QpoBCyKppP0OcxYEdU0hpsaqBBIZOtBajj
# cw5+w/KeFvPYfLF/ldYpmlG+vd0xqlqd099iChnyIMvY5HexjO2AmtsbpVn0OhNc
# WbWDRF/3sBp6fWXhz7DcML4iTAWS+MVXeNLj1lJziVKEoroGs9Mlizg0bUMbOalO
# hOfCipnx8CaLZeVme5yELg09Jlo8BMe80jO37PU8ejfkP9/uPak7VLwELKxAMcJs
# zkyeiaerlphwoKx1uHRzNyE6bxuSKcutisqmKL5OTunAvtONEoteSiabkPVSZ2z7
# 6mKnzAfZxCl/3dq3dUNw4rg3sTCggkHSRqTqlLMS7gjrhTqBmzu1L90Y1KWN/Y5J
# KdGvspbOrTfOXyXvmPL6E52z1NZJ6ctuMFBQZH3pwWvqURR8AgQdULUvrxjUYbHH
# j95Ejza63zdrEcxWLDX6xWls/GDnVNueKjWUH3fTv1Y8Wdho698YADR7TNx8X8z2
# Bev6SivBBOHY+uqiirZtg0y9ShQoPzmCcn63Syatatvx157YK9hlcPmVoa1oDE5/
# L9Uo2bC5a4CH2RwwggY+MIIEpqADAgECAhAHnODk0RR/hc05c892LTfrMA0GCSqG
# SIb3DQEBDAUAMFQxCzAJBgNVBAYTAkdCMRgwFgYDVQQKEw9TZWN0aWdvIExpbWl0
# ZWQxKzApBgNVBAMTIlNlY3RpZ28gUHVibGljIENvZGUgU2lnbmluZyBDQSBSMzYw
# HhcNMjYwMjA5MDAwMDAwWhcNMjkwNDIxMjM1OTU5WjBVMQswCQYDVQQGEwJVUzEU
# MBIGA1UECAwLQ29ubmVjdGljdXQxFzAVBgNVBAoMDkphc29uIEFsYmVyaW5vMRcw
# FQYDVQQDDA5KYXNvbiBBbGJlcmlubzCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCC
# AgoCggIBAPN6aN4B1yYWkI5b5TBj3I0VV/peETrHb6EY4BHGxt8Ap+eT+WpEpJyE
# tRYPxEmNJL3A38Bkg7mwzPE3/1NK570ZBCuBjSAn4mSDIgIuXZnvyBO9W1OQs5d6
# 7MlJLUAEufl18tOr3ST1DeO9gSjQSAE5Nql0QDxPnm93OZBon+Fz3CmE+z3MwAe2
# h4KdtRAnCqwM+/V7iBdbw+JOxolpx+7RVjGyProTENIG3pe/hKvPb501lf8uBAAD
# LdjZr5ip8vIWbf857Yw1Bu10nVI7HW3eE8Cl5//d1ribHlzTzQLfttW+k+DaFsKZ
# BBL56l4YAlIVRsrOiE1kdHYYx6IGrEA809R7+TZA9DzGqyFiv9qmJAbL4fDwetDe
# yIq+Oztz1LvEdy8Rcd0JBY+J4S0eDEFIA3X0N8VcLeAwabKb9AjulKXwUeqCJLvN
# 79CJ90UTZb2+I+tamj0dn+IKMEsJ4v4Ggx72sxFr9+6XziodtTg5Luf2xd6+Phha
# mOxF2px9LObhBLLEMyRsCHZIzVZOFKu9BpHQH7ufGB+Sa80Tli0/6LEyn9+bMYWi
# 2ttn6lLOPThXMiQaooRUq6q2u3+F4SaPlxVFLI7OJVMhar6nW6joBvELTJPmANSM
# jDSRFDfHRCdGbZsL/keELJNy+jZctF6VvxQEjFM8/bazu6qYhrA7AgMBAAGjggGJ
# MIIBhTAfBgNVHSMEGDAWgBQPKssghyi47G9IritUpimqF6TNDDAdBgNVHQ4EFgQU
# 6YF0o0D5AVhKHbVocr8GaSIBibAwDgYDVR0PAQH/BAQDAgeAMAwGA1UdEwEB/wQC
# MAAwEwYDVR0lBAwwCgYIKwYBBQUHAwMwSgYDVR0gBEMwQTA1BgwrBgEEAbIxAQIB
# AwIwJTAjBggrBgEFBQcCARYXaHR0cHM6Ly9zZWN0aWdvLmNvbS9DUFMwCAYGZ4EM
# AQQBMEkGA1UdHwRCMEAwPqA8oDqGOGh0dHA6Ly9jcmwuc2VjdGlnby5jb20vU2Vj
# dGlnb1B1YmxpY0NvZGVTaWduaW5nQ0FSMzYuY3JsMHkGCCsGAQUFBwEBBG0wazBE
# BggrBgEFBQcwAoY4aHR0cDovL2NydC5zZWN0aWdvLmNvbS9TZWN0aWdvUHVibGlj
# Q29kZVNpZ25pbmdDQVIzNi5jcnQwIwYIKwYBBQUHMAGGF2h0dHA6Ly9vY3NwLnNl
# Y3RpZ28uY29tMA0GCSqGSIb3DQEBDAUAA4IBgQAEIsm4xnOd/tZMVrKwi3doAXvC
# wOA/RYQnFJD7R/bSQRu3wXEK4o9SIefye18B/q4fhBkhNAJuEvTQAGfqbbpxow03
# J5PrDTp1WPCWbXKX8Oz9vGWJFyJxRGftkdzZ57JE00synEMS8XCwLO9P32MyR9Z9
# URrpiLPJ9rQjfHMb1BUdvaNayomm7aWLAnD+X7jm6o8sNT5An1cwEAob7obWDM6s
# X93wphwJNBJAstH9Ozs6LwISOX6sKS7CKm9N3Kp8hOUue0ZHAtZdFl6o5u12wy+z
# zieGEI50fKnN77FfNKFOWKlS6OJwlArcbFegB5K89LcE5iNSmaM3VMB2ADV1FEcj
# GSHw4lTg1Wx+WMAMdl/7nbvfFxJ9uu5tNiT54B0s+lZO/HztwXYQUczdsFon3pjs
# Nrsk9ZlalBi5SHkIu+F6g7tWiEv3rtVApmJRnLkUr2Xq2a4nbslUCt4jKs5UX4V1
# nSX8OM++AXoyVGO+iTj7z+pl6XE9Gw/Td6WKKKsxggMaMIIDFgIBATBoMFQxCzAJ
# BgNVBAYTAkdCMRgwFgYDVQQKEw9TZWN0aWdvIExpbWl0ZWQxKzApBgNVBAMTIlNl
# Y3RpZ28gUHVibGljIENvZGUgU2lnbmluZyBDQSBSMzYCEAec4OTRFH+FzTlzz3Yt
# N+swDQYJYIZIAWUDBAIBBQCggYQwGAYKKwYBBAGCNwIBDDEKMAigAoAAoQKAADAZ
# BgkqhkiG9w0BCQMxDAYKKwYBBAGCNwIBBDAcBgorBgEEAYI3AgELMQ4wDAYKKwYB
# BAGCNwIBFTAvBgkqhkiG9w0BCQQxIgQgTjIDAPM9atYOkYz59Q3avEV0MFzaKX75
# D+Sx8Xb1nTcwDQYJKoZIhvcNAQEBBQAEggIApiR+fLw4aIUTQX1GEhUQCFhrLF/p
# z0qoa/cnIlEGYZ9cCgXPYg/1VqwBx7eSsrAXkNS/Z07FFb44F+X9g1woO0Sxks5T
# QnYx8buHu5HWdDFFTfIOAR0PKQ9Rw2naVqe1veVx8trKFAPj4WHPMlC3bYtVaMvG
# xBx7npIpbfRjGS0JrOJRaPjNZ+PKQBC2/hKx48DZKW2sQ8pBtMNx5ZNYqpUv/gCF
# wVdIl3Zdu96splpAuTr7d0B5QirJtrQhlOqrqYZ29MWmVjRLcQcIU3IE3ggBDDfw
# a0zzXvniYZAqDj3QODhIH/uZnJPIsiO8b9gjcKC+3/u2WFV1s23LZkTCeLUAR1Q4
# GwL8ECO4C3BIEa/CTohhJ8Rgxot6ZRCiHYkzyzCJkxZ1aNSXjyV2iiR5zJmxifCy
# DU7eV6H33GZXOeMkQCU817u+GoQjEbIgEMTjAQrgUw2pp6odL+IlWnqQs1yfStk5
# OK3CINsQt/gZFB6Qt4fLId4qb/u0qZr+mpL0Gf+c1BVQKh+XRyxcK1T3xptEam1O
# FKQfpb2CYmKj4OUCg5CniRh+tYkTWhBI9o5GXIewjG3d//4qb5gd9ZPTNehyiDZe
# QigAFMyDfnMjulnTCcB4p1jc4lYp7DtKg3Q8l9cI5vd0zMKo6S+ZL/1L2Pu7ajk/
# k9N2OC7zqhKPEcI=
# SIG # End signature block
