#
# Module manifest for module 'WhatsUpGoldPS'
# Generated by: Jason Alberino
# Generated on: 2023-03-04
#

@{
# Version number of this module.
ModuleVersion = '0.0.2'

# ID used to uniquely identify this module
GUID = '94d2aadd-f227-452e-b48a-c215d243418c'

# Author of this module
Author = 'Jason Alberino'

# Company or vendor of this module
CompanyName = 'Jason Alberino'

# Copyright statement for this module
Copyright = '2023 (c) All rights reserved.'

# Description of the functionality provided by this module
Description = 'Interact with the WhatsUp Gold REST API using PowerShell'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# *
PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# *
PowerShellHostVersion = ''

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = '*'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = '*'

# List of all the files in the helpers directory to be imported.
# Change the file names as per your requirement.
NestedModules = @('helpers\ConvertTo-BootstrapTable.ps1', 'helpers\Convert-HTMLTemplate.ps1')

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
         Tags = @("WhatsUpGold","RESTAPI","WUG")

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/jayyx2/WhatsUpGoldPS/blob/main/LICENSE.md'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/jayyx2/WhatsUpGoldPS'

        # A URL to an icon representing this module.
        IconUri = 'https://wug.ninja/favicon.ico'

        # ReleaseNotes of this module
        ReleaseNotes = 'https://github.com/jayyx2/WhatsUpGoldPS/blob/main/CHANGELOG.md'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
 HelpInfoURI = 'https://github.com/jayyx2/WhatsUpGoldPS/issues'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}